# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
        name: The First Step
        command: |
          echo 'Hello World!'
          echo 'STEP 1'
     - run:
        name: Code Has Arrived
        command: |
          ls -al
          echo 'STEP 2'
     - run:
        name: Running Test  
        command: |
          node -v
          echo 'STEP 3'
  package:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
     - run:
        name: Success
        command: |
          echo 'Success'
workflows:
  version: 2
  build-package:
    jobs:
      - build
      - package
        requires:
          - build
